apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-k8s-app
  namespace: argocd
spec:
  project: my-project

  source:
    repoURL: https://github.com/YOUR_USERNAME/YOUR_REPO.git
    targetRevision: main
    path: .

  destination:
    server: https://172.25.0.3:6443
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
