apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-k8s-portfoliocms
  namespace: argocd
spec:
  project: argocd-portfoliocms

  source:
    repoURL: https://github.com/Qaissumshahaab/argocd_Integrations.git
    targetRevision: main
    path: argoCDkubernetesDeploymentForPortfoliocms/k8s

  destination:
    server: https://172.25.0.3:6443
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
