apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
    
type: Opaque
stringData:
  PORT: "5001"
  MONGODB_URL: ""
  CLOUDINARY_CLOUD_NAME: ""
  CLOUDINARY_API_KEY: ""
  CLOUDINARY_API_SECRET: ""
  FRONTEND_URL: "http://localhost:5173"
